version: "3"

name: network-b
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: network-b-frontend
    restart: always
    env_file:
      - ./.env.production
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./sqlite
        target: /app/sqlite
